// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: keymanager.proto

package kmspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyManager_StartSession_FullMethodName   = "/signet.kms.v1.KeyManager/StartSession"
	KeyManager_ProcessMessage_FullMethodName = "/signet.kms.v1.KeyManager/ProcessMessage"
	KeyManager_AbortSession_FullMethodName   = "/signet.kms.v1.KeyManager/AbortSession"
	KeyManager_GetPublicKey_FullMethodName   = "/signet.kms.v1.KeyManager/GetPublicKey"
	KeyManager_ListKeys_FullMethodName       = "/signet.kms.v1.KeyManager/ListKeys"
)

// KeyManagerClient is the client API for KeyManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KeyManager is the gRPC interface between the signet node (Go) and the KMS
// process (Rust). The node acts as a message router; the KMS holds key material
// and executes FROST protocol rounds.
type KeyManagerClient interface {
	// StartSession initialises a new keygen, signing, or reshare session inside
	// the KMS. The KMS allocates internal state and returns any first-round
	// messages the node should broadcast.
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	// ProcessMessage is a bidirectional stream for the duration of a session.
	// The node feeds incoming peer messages and reads back outgoing messages to
	// forward. The KMS drives the FROST round loop internally.
	ProcessMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionMessage, SessionMessage], error)
	// AbortSession tears down a session, releasing all associated state.
	AbortSession(ctx context.Context, in *AbortSessionRequest, opts ...grpc.CallOption) (*AbortSessionResponse, error)
	// GetPublicKey returns the group public key and this node's verifying share.
	GetPublicKey(ctx context.Context, in *KeyRef, opts ...grpc.CallOption) (*PublicKeyResponse, error)
	// ListKeys returns all key IDs stored for a group.
	ListKeys(ctx context.Context, in *GroupRef, opts ...grpc.CallOption) (*KeyListResponse, error)
}

type keyManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyManagerClient(cc grpc.ClientConnInterface) KeyManagerClient {
	return &keyManagerClient{cc}
}

func (c *keyManagerClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, KeyManager_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagerClient) ProcessMessage(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SessionMessage, SessionMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KeyManager_ServiceDesc.Streams[0], KeyManager_ProcessMessage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SessionMessage, SessionMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyManager_ProcessMessageClient = grpc.BidiStreamingClient[SessionMessage, SessionMessage]

func (c *keyManagerClient) AbortSession(ctx context.Context, in *AbortSessionRequest, opts ...grpc.CallOption) (*AbortSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortSessionResponse)
	err := c.cc.Invoke(ctx, KeyManager_AbortSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagerClient) GetPublicKey(ctx context.Context, in *KeyRef, opts ...grpc.CallOption) (*PublicKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublicKeyResponse)
	err := c.cc.Invoke(ctx, KeyManager_GetPublicKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagerClient) ListKeys(ctx context.Context, in *GroupRef, opts ...grpc.CallOption) (*KeyListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyListResponse)
	err := c.cc.Invoke(ctx, KeyManager_ListKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyManagerServer is the server API for KeyManager service.
// All implementations must embed UnimplementedKeyManagerServer
// for forward compatibility.
//
// KeyManager is the gRPC interface between the signet node (Go) and the KMS
// process (Rust). The node acts as a message router; the KMS holds key material
// and executes FROST protocol rounds.
type KeyManagerServer interface {
	// StartSession initialises a new keygen, signing, or reshare session inside
	// the KMS. The KMS allocates internal state and returns any first-round
	// messages the node should broadcast.
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	// ProcessMessage is a bidirectional stream for the duration of a session.
	// The node feeds incoming peer messages and reads back outgoing messages to
	// forward. The KMS drives the FROST round loop internally.
	ProcessMessage(grpc.BidiStreamingServer[SessionMessage, SessionMessage]) error
	// AbortSession tears down a session, releasing all associated state.
	AbortSession(context.Context, *AbortSessionRequest) (*AbortSessionResponse, error)
	// GetPublicKey returns the group public key and this node's verifying share.
	GetPublicKey(context.Context, *KeyRef) (*PublicKeyResponse, error)
	// ListKeys returns all key IDs stored for a group.
	ListKeys(context.Context, *GroupRef) (*KeyListResponse, error)
	mustEmbedUnimplementedKeyManagerServer()
}

// UnimplementedKeyManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyManagerServer struct{}

func (UnimplementedKeyManagerServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedKeyManagerServer) ProcessMessage(grpc.BidiStreamingServer[SessionMessage, SessionMessage]) error {
	return status.Error(codes.Unimplemented, "method ProcessMessage not implemented")
}
func (UnimplementedKeyManagerServer) AbortSession(context.Context, *AbortSessionRequest) (*AbortSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortSession not implemented")
}
func (UnimplementedKeyManagerServer) GetPublicKey(context.Context, *KeyRef) (*PublicKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublicKey not implemented")
}
func (UnimplementedKeyManagerServer) ListKeys(context.Context, *GroupRef) (*KeyListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKeys not implemented")
}
func (UnimplementedKeyManagerServer) mustEmbedUnimplementedKeyManagerServer() {}
func (UnimplementedKeyManagerServer) testEmbeddedByValue()                    {}

// UnsafeKeyManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyManagerServer will
// result in compilation errors.
type UnsafeKeyManagerServer interface {
	mustEmbedUnimplementedKeyManagerServer()
}

func RegisterKeyManagerServer(s grpc.ServiceRegistrar, srv KeyManagerServer) {
	// If the following call panics, it indicates UnimplementedKeyManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyManager_ServiceDesc, srv)
}

func _KeyManager_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagerServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManager_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagerServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManager_ProcessMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeyManagerServer).ProcessMessage(&grpc.GenericServerStream[SessionMessage, SessionMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyManager_ProcessMessageServer = grpc.BidiStreamingServer[SessionMessage, SessionMessage]

func _KeyManager_AbortSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagerServer).AbortSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManager_AbortSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagerServer).AbortSession(ctx, req.(*AbortSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManager_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagerServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManager_GetPublicKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagerServer).GetPublicKey(ctx, req.(*KeyRef))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManager_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupRef)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagerServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManager_ListKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagerServer).ListKeys(ctx, req.(*GroupRef))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyManager_ServiceDesc is the grpc.ServiceDesc for KeyManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "signet.kms.v1.KeyManager",
	HandlerType: (*KeyManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSession",
			Handler:    _KeyManager_StartSession_Handler,
		},
		{
			MethodName: "AbortSession",
			Handler:    _KeyManager_AbortSession_Handler,
		},
		{
			MethodName: "GetPublicKey",
			Handler:    _KeyManager_GetPublicKey_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _KeyManager_ListKeys_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessMessage",
			Handler:       _KeyManager_ProcessMessage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "keymanager.proto",
}
