[package]
name = "signet-near"
version = "0.1.0"
edition = "2021"
authors = ["Oleary Labs"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "5.26"
sha2 = "0.10"

[dev-dependencies]
near-sdk = { version = "5.26", features = ["unit-testing"] }

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
