package node

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/fxamacker/cbor/v2"
	libp2pnet "github.com/libp2p/go-libp2p/core/network"
	"github.com/libp2p/go-libp2p/core/protocol"
	"go.uber.org/zap"

	"signet/network"
	"signet/tss"
)

const coordProtocol = protocol.ID("/signet/coord/1.0.0")

// Coord stream ACK/NACK responses. The participant writes a single byte after
// processing the coord message to indicate readiness.
const (
	coordNACK byte = 0 // rejected — peer cannot participate
	coordACK  byte = 1 // accepted — peer is ready to run the protocol
)

type coordMsgType uint8

const (
	msgKeygen          coordMsgType = 1
	msgSign            coordMsgType = 2
	msgReshare         coordMsgType = 3
	msgReshareComplete coordMsgType = 4
	msgReshareBatch    coordMsgType = 5
	msgReshareCommit   coordMsgType = 6
	msgDelegateSign    coordMsgType = 7
	msgAuth            coordMsgType = 8  // forward auth proof to establish session on participants
	msgSetKeyStatus    coordMsgType = 9  // set key status (active/disabled) across all nodes
	msgDeleteKey       coordMsgType = 10 // permanently delete a key across all nodes
)

// coordMsg is sent from the initiating node to each other participant to start
// a keygen or sign session.
//
// GroupID and KeyID identify the key shard in storage. For keygen, the
// internal session string is derived as groupID+":"+keyID. For sign, SignNonce
// (a random string generated by the initiator) is appended to disambiguate
// concurrent signing sessions on the same key.
type coordMsg struct {
	Type coordMsgType `cbor:"1,keyasint"`

	// Both keygen and sign: identify the key.
	GroupID   string     `cbor:"2,keyasint,omitempty"`
	KeyID     string     `cbor:"3,keyasint,omitempty"`
	Parties   []tss.PartyID `cbor:"4,keyasint,omitempty"`
	Threshold int        `cbor:"5,keyasint,omitempty"`

	// Sign only: random nonce generated by initiator so all peers derive the
	// same session protocol ID, plus signing parameters.
	SignNonce   string     `cbor:"6,keyasint,omitempty"`
	Signers     []tss.PartyID `cbor:"7,keyasint,omitempty"`
	MessageHash []byte     `cbor:"8,keyasint,omitempty"`

	// Auth: full auth proof — only used in msgAuth to establish sessions
	// on participants. Keygen/sign/delegate use SessionAuth instead.
	Auth *AuthProof `cbor:"10,keyasint,omitempty"`

	// Session: lightweight session credential for keygen/sign/delegate.
	// Participants verify the request signature against a cached session.
	Session *SessionAuth `cbor:"21,keyasint,omitempty"`

	// Curve: "secp256k1", "ed25519", or "ecdsa_secp256k1". Empty defaults to "secp256k1".
	Curve string `cbor:"16,keyasint,omitempty"`

	// Scope: signing scope constraint bytes (keygen only). Empty = unscoped.
	Scope []byte `cbor:"18,keyasint,omitempty"`

	// SignPayload: structured signing payload for scoped keys (sign only).
	// JSON-encoded SignPayload. Participants verify scope independently.
	SignPayload []byte `cbor:"19,keyasint,omitempty"`

	// DelegateSubKey: the sub-key ID being delegated (msgDelegateSign only).
	// The client's request signature is over this key ID, not the parent
	// key in KeyID. Each participant verifies auth against this field and
	// checks that it's under the same identity namespace as KeyID.
	DelegateSubKey string `cbor:"20,keyasint,omitempty"`

	// Key lifecycle: status for msgSetKeyStatus ("active" or "disabled").
	KeyStatus string `cbor:"22,keyasint,omitempty"`

	// Reshare only: old and new committee definitions.
	OldParties   []tss.PartyID `cbor:"11,keyasint,omitempty"`
	NewParties   []tss.PartyID `cbor:"12,keyasint,omitempty"`
	NewThreshold int           `cbor:"13,keyasint,omitempty"`
	ReshareNonce string        `cbor:"14,keyasint,omitempty"`

	// ReshareBatch only: list of (keyID, nonce) pairs for batch reshare.
	// Sent once per batch instead of one coord stream per key.
	BatchKeys []reshareBatchKey `cbor:"15,keyasint,omitempty"`
}

// reshareBatchKey is a single key in a reshare batch.
type reshareBatchKey struct {
	KeyID string `cbor:"1,keyasint"`
	Nonce string `cbor:"2,keyasint"`
}

// keygenSessionID returns the deterministic internal session string for a keygen.
func keygenSessionID(groupID, keyID string) string {
	return groupID + ":" + keyID
}

// signSessionID returns the internal session string for a sign, incorporating
// a random nonce to allow concurrent signs on the same key.
func signSessionID(groupID, keyID, nonce string) string {
	return groupID + ":" + keyID + ":" + nonce
}

// reshareSessionID returns the internal session string for a reshare.
// The nonce distinguishes concurrent reshare attempts on the same key
// (e.g. coordinator vs on-demand).
func reshareSessionID(groupID, keyID, nonce string) string {
	return groupID + ":reshare:" + keyID + ":" + nonce
}

// registerCoordHandler registers the /signet/coord/1.0.0 stream handler on the
// node's libp2p host.
func (n *Node) registerCoordHandler() {
	n.host.LibP2PHost().SetStreamHandler(coordProtocol, n.handleCoordStream)
}

// handleCoordStream handles an incoming coordination request from an initiator.
// It registers a session stream handler, sends a ready ACK, then runs the
// protocol in a background goroutine.
// groupState returns the active member set and threshold for a group from this
// node's own on-chain-derived state (n.groups). Participants use it to validate
// initiator-supplied protocol parameters rather than trusting the coord message
// (H1). ok is false if the group is unknown locally.
func (n *Node) groupState(groupID string) (members map[tss.PartyID]bool, threshold int, ok bool) {
	n.groupsMu.RLock()
	grp := n.groups[groupID]
	n.groupsMu.RUnlock()
	if grp == nil || len(grp.Members) == 0 {
		return nil, 0, false
	}
	members = make(map[tss.PartyID]bool, len(grp.Members))
	for _, p := range grp.Members {
		members[p] = true
	}
	return members, grp.Threshold, true
}

// checkKeygenParams validates initiator-supplied keygen parameters against the
// group's on-chain state: the threshold must match exactly and every party must
// be an active member (subset allowed). Returns nil if acceptable.
func checkKeygenParams(members map[tss.PartyID]bool, groupThreshold int, parties []tss.PartyID, msgThreshold int) error {
	if msgThreshold != groupThreshold {
		return fmt.Errorf("threshold mismatch: msg=%d group=%d", msgThreshold, groupThreshold)
	}
	if len(parties) == 0 {
		return fmt.Errorf("empty party set")
	}
	for _, p := range parties {
		if !members[p] {
			return fmt.Errorf("party not in group: %s", p)
		}
	}
	return nil
}

// checkSignerSet validates an initiator-supplied signer set: every signer must
// be an active member and the count of distinct signers must be at least the
// group threshold. Returns nil if acceptable.
func checkSignerSet(members map[tss.PartyID]bool, groupThreshold int, signers []tss.PartyID) error {
	distinct := make(map[tss.PartyID]bool, len(signers))
	for _, s := range signers {
		if !members[s] {
			return fmt.Errorf("signer not in group: %s", s)
		}
		distinct[s] = true
	}
	if len(distinct) < groupThreshold {
		return fmt.Errorf("signer set below threshold: %d < %d", len(distinct), groupThreshold)
	}
	return nil
}

func (n *Node) handleCoordStream(s libp2pnet.Stream) {
	defer s.Close()

	var msg coordMsg
	if err := cbor.NewDecoder(s).Decode(&msg); err != nil {
		n.log.Warn("coord: decode msg", zap.Error(err))
		return
	}

	// ---------- msgAuth: establish session on this participant ----------
	if msg.Type == msgAuth {
		if msg.Auth == nil {
			n.log.Warn("coord: msgAuth missing proof")
			s.Write([]byte{coordNACK})
			return
		}

		var keyPrefix string
		var sessionExp time.Time

		if msg.Auth.DelegationToken != "" {
			// Delegation token path: verify the token independently.
			claims, err := n.VerifyDelegationToken(msg.GroupID, msg.Auth.DelegationToken)
			if err != nil {
				n.log.Warn("coord: delegation token invalid",
					zap.String("group_id", msg.GroupID),
					zap.Error(err))
				s.Write([]byte{coordNACK})
				return
			}
			// Extract iss/sub from the delegation token's sub-key ID so the
			// session resolves through the oauth path (not authkey).
			delIss, delSub := parseDelegationIdentity(claims.Sub)
			msg.Auth.Iss = delIss
			msg.Auth.Sub = delSub
			keyPrefix = "oauth:" + delIss + ":" + delSub
			sessionExp = time.Unix(claims.Exp, 0)
		} else {
			// ZK proof or auth key certificate path.
			var err error
			keyPrefix, err = n.auth.ValidateAuthProof(n.ctx, msg.GroupID, msg.Auth)
			if err != nil {
				n.log.Warn("coord: auth proof invalid",
					zap.String("group_id", msg.GroupID),
					zap.Error(err))
				s.Write([]byte{coordNACK})
				return
			}
			sessionExp = time.Unix(int64(msg.Auth.Exp), 0)
		}

		sessionHex := sessionPubToHex(msg.Auth.SessionPub)
		si := &SessionInfo{
			Sub:           msg.Auth.Sub,
			Iss:           msg.Auth.Iss,
			Exp:           sessionExp,
			Aud:           msg.Auth.Aud,
			Azp:           msg.Auth.Azp,
			AuthKeyPub:    msg.Auth.AuthKeyPub,
			CertSignature: msg.Auth.CertSignature,
			Identity:      msg.Auth.Identity,
		}
		// For delegation token sessions, lock to the delegated sub-key.
		if msg.Auth.DelegationToken != "" {
			// claims was already verified above in the delegation path.
			claims, _ := n.VerifyDelegationToken(msg.GroupID, msg.Auth.DelegationToken)
			if claims != nil {
				si.DelegatedKeyID = "oauth:" + claims.Sub
			}
		}
		n.sessions.Put(sessionHex, si)
		n.log.Info("coord: session established",
			zap.String("group_id", msg.GroupID),
			zap.String("identity", keyPrefix),
			zap.String("session_pub", sessionHex))
		s.Write([]byte{coordACK})
		return
	}

	// ---------- Session auth for keygen/sign/delegate ----------
	// These operations require a previously established session. The coord
	// message carries a lightweight SessionAuth (session pub + request sig).
	// No ZK proof — that was verified once during msgAuth.
	requiresUserAuth := msg.Type == msgKeygen || msg.Type == msgSign || msg.Type == msgDelegateSign ||
		msg.Type == msgSetKeyStatus || msg.Type == msgDeleteKey
	if requiresUserAuth && n.auth.HasAuthPolicy(msg.GroupID) {
		if msg.Session == nil {
			n.log.Warn("coord: missing session auth",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
			s.Write([]byte{coordNACK})
			return
		}

		// Look up cached session.
		sessionHex := sessionPubToHex(msg.Session.SessionPub)
		cached, ok := n.sessions.Get(sessionHex)
		if !ok || time.Now().After(cached.Exp) {
			n.log.Warn("coord: session not found or expired",
				zap.String("group_id", msg.GroupID),
				zap.String("session_pub", sessionHex))
			s.Write([]byte{coordNACK})
			return
		}

		// Build identity prefix from cached session.
		var keyPrefix string
		if cached.Identity != "" {
			keyPrefix = "authkey:" + cached.Identity
		} else {
			keyPrefix = "oauth:" + cached.Iss + ":" + cached.Sub
		}

		// For delegate-sign, the client signed the request over the sub-key
		// ID (authorizing delegation of that specific sub-key). Verify against
		// the sub-key, then confirm it's under the same identity as the parent.
		authKeyID := msg.KeyID
		if msg.Type == msgDelegateSign {
			if msg.DelegateSubKey == "" {
				n.log.Warn("coord: delegate-sign missing sub-key")
				s.Write([]byte{coordNACK})
				return
			}
			authKeyID = msg.DelegateSubKey
			parentNS := stripKeyNamespace(msg.KeyID)
			subNS := stripKeyNamespace(msg.DelegateSubKey)
			if !strings.HasPrefix(subNS, parentNS+":") {
				n.log.Warn("coord: delegate sub-key not under parent namespace",
					zap.String("parent", msg.KeyID),
					zap.String("sub_key", msg.DelegateSubKey))
				s.Write([]byte{coordNACK})
				return
			}
		}

		// Verify request signature against the logical key_id.
		logicalKeyID := stripKeyNamespace(authKeyID)
		var msgHash []byte
		if msg.Type == msgSign {
			if len(msg.SignPayload) > 0 {
				// Scoped signing: the client signed the request over the
				// payload hash it computed itself (EIP-712 hashTypedData).
				// Recompute it from the forwarded payload so the session
				// signature binds the exact payload — a malicious initiator
				// cannot substitute a different payload under the same scope.
				var payload SignPayload
				if err := json.Unmarshal(msg.SignPayload, &payload); err != nil {
					n.log.Warn("coord: parse sign payload for auth",
						zap.String("group_id", msg.GroupID),
						zap.Error(err))
					return
				}
				hash, err := HashSignPayload(&payload)
				if err != nil {
					n.log.Warn("coord: hash sign payload for auth",
						zap.String("group_id", msg.GroupID),
						zap.Error(err))
					return
				}
				msgHash = hash
			} else {
				// Unscoped signing: raw message hash.
				msgHash = msg.MessageHash
			}
		}
		if err := verifyRequestSignature(
			msg.Session.SessionPub, msg.Session.RequestSig,
			msg.GroupID, logicalKeyID, msg.Session.Nonce, msg.Session.Timestamp,
			msgHash,
		); err != nil {
			n.log.Warn("coord: invalid request signature",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Error(err))
			return
		}
		// Check nonce uniqueness.
		if err := n.sessions.CheckNonce(msg.Session.Nonce); err != nil {
			n.log.Warn("coord: nonce replay",
				zap.String("group_id", msg.GroupID),
				zap.String("nonce", msg.Session.Nonce))
			return
		}
		// Check timestamp freshness.
		ts := time.Unix(int64(msg.Session.Timestamp), 0)
		if time.Since(ts).Abs() > timestampWindow {
			n.log.Warn("coord: timestamp out of range",
				zap.String("group_id", msg.GroupID),
				zap.Uint64("timestamp", msg.Session.Timestamp))
			return
		}
		// KeyID must match auth identity prefix.
		if msg.KeyID != keyPrefix && !strings.HasPrefix(msg.KeyID, keyPrefix+":") {
			n.log.Warn("coord: key_id does not match auth identity",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.String("key_prefix", keyPrefix))
			return
		}
	}

	switch msg.Type {
	case msgKeygen:
		kgCurve := Curve(msg.Curve)
		if kgCurve == "" {
			kgCurve = CurveSecp256k1
		}

		// H1: validate keygen parameters against local on-chain group state. A
		// malicious initiator must not be able to pick an off-chain party set or
		// a threshold that differs from the group contract.
		members, threshold, ok := n.groupState(msg.GroupID)
		if !ok {
			n.log.Warn("coord: keygen for unknown group", zap.String("group_id", msg.GroupID))
			s.Write([]byte{coordNACK})
			return
		}
		if err := checkKeygenParams(members, threshold, msg.Parties, msg.Threshold); err != nil {
			n.log.Warn("coord: keygen params rejected",
				zap.String("group_id", msg.GroupID), zap.Error(err))
			s.Write([]byte{coordNACK})
			return
		}

		if info, _ := n.km.GetKeyInfo(msg.GroupID, msg.KeyID, kgCurve); info != nil {
			n.log.Warn("coord: keygen rejected, key already exists",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
			s.Write([]byte{coordNACK})
			return
		}

		sessID := keygenSessionID(msg.GroupID, msg.KeyID)
		sessCtx, sessCancel := context.WithTimeout(n.ctx, 30*time.Second)
		sn, err := network.NewSessionNetwork(sessCtx, n.host, sessID, msg.Parties)
		if err != nil {
			sessCancel()
			n.log.Error("coord: keygen session network",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Error(err))
			return
		}

		// Register pending keygen BEFORE ACK so a racing sign coord handler
		// will see the pending flag and wait rather than returning "key not found".
		n.markKeygenPending(msg.GroupID, msg.KeyID)

		// ACK only after registering the session stream handler, so the
		// initiator knows all parties are ready before starting the protocol.
		s.Write([]byte{coordACK})

		go func() {
			defer sessCancel()
			defer sn.Close()
			defer n.markKeygenDone(msg.GroupID, msg.KeyID)
			n.log.Info("coord: keygen started",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
			curve := Curve(msg.Curve)
			if curve == "" {
				curve = CurveSecp256k1
			}
			_, err := n.km.RunKeygen(sessCtx, KeygenParams{
				Host:      n.host,
				SN:        sn,
				SessionID: sessID,
				GroupID:   msg.GroupID,
				KeyID:     msg.KeyID,
				Parties:   msg.Parties,
				Threshold: msg.Threshold,
				Curve:     curve,
				Scope:     msg.Scope,
			})
			if err != nil {
				n.log.Error("coord: keygen failed",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID),
					zap.Error(err))
				return
			}
			n.log.Info("coord: keygen complete",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
		}()

	case msgSign:
		// H1: validate the signer set against local on-chain group state. A
		// malicious initiator must not be able to include a non-member signer or
		// drive the signer count below the group threshold.
		members, threshold, ok := n.groupState(msg.GroupID)
		if !ok {
			n.log.Warn("coord: sign for unknown group", zap.String("group_id", msg.GroupID))
			return
		}
		if err := checkSignerSet(members, threshold, msg.Signers); err != nil {
			n.log.Warn("coord: signer set rejected",
				zap.String("group_id", msg.GroupID), zap.Error(err))
			return
		}

		sessID := signSessionID(msg.GroupID, msg.KeyID, msg.SignNonce)
		sessCtx, sessCancel := context.WithTimeout(n.ctx, 30*time.Second)
		sn, err := network.NewSessionNetwork(sessCtx, n.host, sessID, msg.Signers)
		if err != nil {
			sessCancel()
			n.log.Error("coord: sign session network",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Error(err))
			return
		}
		s.Write([]byte{coordACK})

		go func() {
			defer sessCancel()
			defer sn.Close()

			curve := Curve(msg.Curve)
			if curve == "" {
				curve = CurveSecp256k1
			}

			n.log.Info("coord: sign started",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))

			// Wait for any pending keygen to finish before attempting to sign.
			info, err := n.awaitKey(msg.GroupID, msg.KeyID, curve, 10*time.Second)
			if err != nil {
				n.log.Error("coord: load config",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID),
					zap.Error(err))
				return
			}
			if info == nil {
				n.log.Error("coord: key not found",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID))
				return
			}
			if info.Status == "disabled" {
				n.log.Warn("coord: sign rejected, key is disabled",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID))
				return
			}

			// Scope enforcement: if the key has a scope, participants
			// independently verify the payload and compute the hash.
			msgHashForSign := msg.MessageHash
			if len(info.Scope) > 0 {
				if len(msg.SignPayload) == 0 {
					n.log.Error("coord: scoped key requires payload",
						zap.String("group_id", msg.GroupID),
						zap.String("key_id", msg.KeyID))
					return
				}
				var payload SignPayload
				if err := json.Unmarshal(msg.SignPayload, &payload); err != nil {
					n.log.Error("coord: parse sign payload",
						zap.String("group_id", msg.GroupID),
						zap.Error(err))
					return
				}
				hash, err := VerifyScopeAndHash(info.Scope, &payload)
				if err != nil {
					n.log.Error("coord: scope verification failed",
						zap.String("group_id", msg.GroupID),
						zap.String("key_id", msg.KeyID),
						zap.Error(err))
					return
				}
				msgHashForSign = hash
			} else if len(msg.SignPayload) > 0 {
				// Unscoped key must not carry a payload: the session
				// signature was verified against the payload hash, so
				// signing msg.MessageHash here would let the initiator
				// sign an arbitrary hash the client never authorized.
				n.log.Error("coord: payload provided for unscoped key",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID))
				return
			}

			_, err = n.km.RunSign(sessCtx, SignParams{
				Host:        n.host,
				SN:          sn,
				SessionID:   sessID,
				GroupID:     msg.GroupID,
				KeyID:       msg.KeyID,
				Signers:     msg.Signers,
				MessageHash: msgHashForSign,
				Curve:       curve,
			})
			if err != nil {
				n.log.Error("coord: sign failed",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID),
					zap.Error(err))
				return
			}
			n.log.Info("coord: sign complete",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
		}()

	case msgDelegateSign:
		// Auth-gated sign for delegation token minting. The parent key (KeyID)
		// signs the JWT hash. Auth was verified above against DelegateSubKey.
		sessID := signSessionID(msg.GroupID, msg.KeyID, msg.SignNonce)
		sessCtx, sessCancel := context.WithTimeout(n.ctx, 30*time.Second)
		sn, err := network.NewSessionNetwork(sessCtx, n.host, sessID, msg.Signers)
		if err != nil {
			sessCancel()
			n.log.Error("coord: delegate-sign session network",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Error(err))
			return
		}
		s.Write([]byte{coordACK})

		go func() {
			defer sessCancel()
			defer sn.Close()

			curve := Curve(msg.Curve)
			if curve == "" {
				curve = CurveSecp256k1
			}

			n.log.Info("coord: delegate-sign started",
				zap.String("group_id", msg.GroupID),
				zap.String("parent_key", msg.KeyID),
				zap.String("sub_key", msg.DelegateSubKey))

			info, err := n.awaitKey(msg.GroupID, msg.KeyID, curve, 10*time.Second)
			if err != nil || info == nil {
				n.log.Error("coord: delegate-sign parent key not found",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID),
					zap.Error(err))
				return
			}
			if info.Status == "disabled" {
				n.log.Warn("coord: delegate-sign rejected, parent key is disabled",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID))
				return
			}

			// Verify the sub-key exists on this node too.
			subInfo, err := n.km.GetKeyInfo(msg.GroupID, msg.DelegateSubKey, curve)
			if err != nil || subInfo == nil {
				n.log.Error("coord: delegate-sign sub-key not found",
					zap.String("group_id", msg.GroupID),
					zap.String("sub_key", msg.DelegateSubKey),
					zap.Error(err))
				return
			}
			if subInfo.Status == "disabled" {
				n.log.Warn("coord: delegate-sign rejected, sub-key is disabled",
					zap.String("group_id", msg.GroupID),
					zap.String("sub_key", msg.DelegateSubKey))
				return
			}

			_, err = n.km.RunSign(sessCtx, SignParams{
				Host:        n.host,
				SN:          sn,
				SessionID:   sessID,
				GroupID:     msg.GroupID,
				KeyID:       msg.KeyID,
				Signers:     msg.Signers,
				MessageHash: msg.MessageHash,
				Curve:       curve,
			})
			if err != nil {
				n.log.Error("coord: delegate-sign failed",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID),
					zap.Error(err))
				return
			}
			n.log.Info("coord: delegate-sign complete",
				zap.String("group_id", msg.GroupID),
				zap.String("parent_key", msg.KeyID),
				zap.String("sub_key", msg.DelegateSubKey))
		}()

	case msgReshare:
		// Compute curve for reshare early — needed for storage lookups.
		msgCurve := Curve(msg.Curve)
		if msgCurve == "" {
			msgCurve = CurveSecp256k1
		}
		// Peer authorization: verify the sender is a group member AND either
		// the elected leader or this node independently knows a reshare is
		// needed (has a local job). This allows the leader-driven path
		// (event-triggered, prevents races) and the on-demand path (any
		// member can coordinate when a sign request hits a stale key).
		senderPeerID := tss.PartyID(s.Conn().RemotePeer().String())
		_, leaderKnown := n.reshareLeader(msg.GroupID)
		if !leaderKnown {
			n.log.Warn("coord: reshare rejected, unknown group",
				zap.String("group_id", msg.GroupID))
			s.Write([]byte{coordNACK})
			return
		}
		// Verify sender is a member of the group (old or new committee).
		n.groupsMu.RLock()
		grpInfo := n.groups[msg.GroupID]
		n.groupsMu.RUnlock()
		senderIsMember := false
		if grpInfo != nil {
			for _, m := range grpInfo.Members {
				if m == senderPeerID {
					senderIsMember = true
					break
				}
			}
		}
		if !senderIsMember {
			n.log.Warn("coord: reshare rejected, sender not in group",
				zap.String("group_id", msg.GroupID),
				zap.String("sender", string(senderPeerID)))
			s.Write([]byte{coordNACK})
			return
		}

		if n.reshareStore == nil {
			n.log.Warn("coord: reshare rejected, reshare store not initialized")
			s.Write([]byte{coordNACK})
			return
		}

		// Only accept if this node has independently observed the need for a
		// reshare (via chain events or admin API). Don't auto-create jobs from
		// untrusted coord messages — the node's own chain poller creates jobs
		// when it sees membership change events.
		job, err := n.reshareStore.GetJob(msg.GroupID)
		if err != nil || job == nil {
			n.log.Warn("coord: reshare rejected, no local job (waiting for chain event)",
				zap.String("group_id", msg.GroupID),
				zap.String("sender", string(senderPeerID)))
			s.Write([]byte{coordNACK})
			return
		}

		// Check if this key is already done for this job. If so, a previous
		// reshare partially succeeded: this node committed but the coordinator
		// didn't. Roll back to the previous version so we can re-participate
		// with consistent key state.
		done, _ := n.reshareStore.IsKeyDone(msg.GroupID, msg.KeyID)
		if done {
			info, _ := n.km.GetKeyInfo(msg.GroupID, msg.KeyID, msgCurve)
			if info != nil {
				// Active key is at generation N (post-reshare). Roll back to N-1.
				gen := uint64(0) // default: roll back to generation 0
				// Read current config to determine generation.
				if lkm, ok := n.km.(*LocalKeyManager); ok {
					if cfg, err := lkm.loadConfig(msg.GroupID, msg.KeyID); err == nil && cfg != nil && cfg.Generation > 0 {
						gen = cfg.Generation - 1
					}
				}
				if err := n.km.RollbackReshare(msg.GroupID, msg.KeyID, msgCurve, gen); err != nil {
					n.log.Error("coord: reshare rollback failed, NACKing",
						zap.String("group_id", msg.GroupID),
						zap.String("key_id", msg.KeyID),
						zap.Uint64("target_generation", gen),
						zap.Error(err))
					s.Write([]byte{coordNACK})
					return
				}
				n.log.Warn("coord: reshare rollback for partial commit",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID),
					zap.Uint64("restored_generation", gen))
			}
			n.reshareStore.DeleteKeyDone(msg.GroupID, msg.KeyID)
			// Fall through to normal participation.
		}

		// Check/register per-key reshare channel. If another session is
		// already running for this key, NACK to avoid duplicates.
		if !n.tryRegisterReshareKey(msg.GroupID, msg.KeyID) {
			n.log.Debug("coord: reshare NACK, session already running",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
			s.Write([]byte{coordNACK})
			return
		}

		// Discard any stale pending result from a previous failed attempt.
		n.km.DiscardPendingReshare(msg.GroupID, msg.KeyID, msgCurve)

		allParties := msg.Parties // old ∪ new
		sessID := reshareSessionID(msg.GroupID, msg.KeyID, msg.ReshareNonce)
		sessCtx, sessCancel := context.WithTimeout(n.ctx, 15*time.Second)
		sn := n.reshareMux.Session(sessCtx, sessID, allParties)

		s.Write([]byte{coordACK})

		go func() {
			defer sessCancel()
			defer sn.Close()

			n.log.Info("coord: reshare started",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))

			// Wait for the first protocol message before committing to the
			// full session timeout. If the coordinator's broadcast partially
			// failed, it won't call RunReshare and no round-1 message will
			// arrive. Detect this quickly so we release the key registration
			// and don't block retries.
			select {
			case firstMsg, ok := <-sn.Incoming():
				if !ok || firstMsg == nil {
					n.completeReshareKey(msg.GroupID, msg.KeyID, false)
					n.log.Warn("coord: reshare aborted, no first message",
						zap.String("group_id", msg.GroupID),
						zap.String("key_id", msg.KeyID))
					return
				}
				// Deliver the message to the protocol by re-enqueueing it.
				sn.Redeliver(firstMsg)
			case <-time.After(10 * time.Second):
				n.completeReshareKey(msg.GroupID, msg.KeyID, false)
				n.log.Warn("coord: reshare aborted, coordinator did not start",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID))
				return
			case <-sessCtx.Done():
				n.completeReshareKey(msg.GroupID, msg.KeyID, false)
				return
			}

			reshCurve := Curve(msg.Curve)
			if reshCurve == "" {
				reshCurve = CurveSecp256k1
			}
			result, err := n.km.RunReshare(sessCtx, ReshareParams{
				Host:         n.host,
				SN:           sn,
				SessionID:    sessID,
				GroupID:      msg.GroupID,
				KeyID:        msg.KeyID,
				OldParties:   msg.OldParties,
				NewParties:   msg.NewParties,
				OldThreshold: msg.Threshold,
				NewThreshold: msg.NewThreshold,
				Curve:        reshCurve,
			})
			if err != nil {
				n.km.DiscardPendingReshare(msg.GroupID, msg.KeyID, reshCurve)
				n.completeReshareKey(msg.GroupID, msg.KeyID, false)
				n.log.Error("coord: reshare failed",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", msg.KeyID),
					zap.Error(err))
				return
			}

			// Protocol succeeded — result is in pending store. Signal that
			// pending is ready so the commit handler can proceed, then release
			// the key registration so retries aren't blocked.
			n.signalPendingReady(msg.GroupID, msg.KeyID)
			n.completeReshareKey(msg.GroupID, msg.KeyID, false)
			n.log.Info("coord: reshare protocol done, awaiting commit",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Uint64("generation", result.Generation))
		}()

	case msgReshareBatch:
		if n.reshareStore == nil {
			n.log.Warn("coord: reshare batch rejected, reshare store not initialized")
			s.Write([]byte{coordNACK})
			return
		}

		job, err := n.reshareStore.GetJob(msg.GroupID)
		if err != nil || job == nil {
			// Auto-create job for API-triggered refresh.
			if err := n.createReshareJob(msg.GroupID, "refresh", msg.OldParties, msg.NewParties, msg.Threshold); err != nil {
				n.log.Warn("coord: reshare batch rejected, could not create job",
					zap.String("group_id", msg.GroupID), zap.Error(err))
				s.Write([]byte{coordNACK})
				return
			}
		}

		allParties := msg.Parties
		s.Write([]byte{coordACK})

		n.log.Info("coord: reshare batch received",
			zap.String("group_id", msg.GroupID),
			zap.Int("keys", len(msg.BatchKeys)))

		// Process each key in the batch sequentially (coordinator controls
		// concurrency via how many batches it sends in parallel).
		for _, bk := range msg.BatchKeys {
			done, _ := n.reshareStore.IsKeyDone(msg.GroupID, bk.KeyID)
			if done {
				continue
			}
			if !n.tryRegisterReshareKey(msg.GroupID, bk.KeyID) {
				continue // already running
			}

			sessID := reshareSessionID(msg.GroupID, bk.KeyID, bk.Nonce)
			sessCtx, sessCancel := context.WithTimeout(n.ctx, 15*time.Second)
			sn := n.reshareMux.Session(sessCtx, sessID, allParties)

			batchCurve := Curve(msg.Curve)
			if batchCurve == "" {
				batchCurve = CurveSecp256k1
			}
			result, err := n.km.RunReshare(sessCtx, ReshareParams{
				Host:         n.host,
				SN:           sn,
				SessionID:    sessID,
				GroupID:      msg.GroupID,
				KeyID:        bk.KeyID,
				OldParties:   msg.OldParties,
				NewParties:   msg.NewParties,
				OldThreshold: msg.Threshold,
				NewThreshold: msg.NewThreshold,
				Curve:        batchCurve,
			})
			sessCancel()
			sn.Close()

			if err != nil {
				n.completeReshareKey(msg.GroupID, bk.KeyID, false)
				n.log.Error("coord: reshare batch key failed",
					zap.String("group_id", msg.GroupID),
					zap.String("key_id", bk.KeyID),
					zap.Error(err))
				continue
			}

			n.reshareStore.PutKeyDone(msg.GroupID, bk.KeyID, &ReshareKeyRecord{
				CompletedAt: time.Now(),
				ByNode:      string(n.host.Self()),
				OldOnly:     result.OldOnly,
			})
			n.completeReshareKey(msg.GroupID, bk.KeyID, true)
		}

	case msgReshareCommit:
		commitCurve := Curve(msg.Curve)
		if commitCurve == "" {
			commitCurve = CurveSecp256k1
		}
		// Coordinator says the reshare protocol succeeded on all nodes.
		// Wait for the participant's reshare goroutine to finish writing
		// the pending result — the commit can arrive before the local
		// RunReshare has written to the pending store.
		n.waitPendingReady(msg.GroupID, msg.KeyID, 10*time.Second)

		// Promote pending result to active and record completion.
		if err := n.km.CommitReshare(msg.GroupID, msg.KeyID, commitCurve); err != nil {
			n.log.Error("coord: reshare commit failed",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Error(err))
			s.Write([]byte{coordNACK})
			return
		}
		n.reshareStore.PutKeyDone(msg.GroupID, msg.KeyID, &ReshareKeyRecord{
			CompletedAt: time.Now(),
			ByNode:      string(n.host.Self()),
		})
		n.completeReshareKey(msg.GroupID, msg.KeyID, true)
		n.log.Info("coord: reshare committed",
			zap.String("group_id", msg.GroupID),
			zap.String("key_id", msg.KeyID))
		s.Write([]byte{coordACK})

	case msgReshareComplete:
		groupID := msg.GroupID
		n.log.Info("coord: reshare complete received, cleaning up",
			zap.String("group_id", groupID))
		n.completeReshareJob(groupID)
		s.Write([]byte{coordACK})

	case msgSetKeyStatus:
		curve := Curve(msg.Curve)
		if curve == "" {
			curve = CurveSecp256k1
		}
		if msg.KeyStatus != "active" && msg.KeyStatus != "disabled" {
			n.log.Warn("coord: invalid key status",
				zap.String("status", msg.KeyStatus))
			s.Write([]byte{coordNACK})
			return
		}
		// Verify the key exists on this node.
		info, err := n.km.GetKeyInfo(msg.GroupID, msg.KeyID, curve)
		if err != nil || info == nil {
			n.log.Warn("coord: set-key-status key not found",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
			s.Write([]byte{coordNACK})
			return
		}
		if err := n.km.SetKeyStatus(msg.GroupID, msg.KeyID, curve, msg.KeyStatus); err != nil {
			n.log.Error("coord: set-key-status failed",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Error(err))
			s.Write([]byte{coordNACK})
			return
		}
		n.log.Info("coord: key status changed",
			zap.String("group_id", msg.GroupID),
			zap.String("key_id", msg.KeyID),
			zap.String("status", msg.KeyStatus))
		s.Write([]byte{coordACK})

	case msgDeleteKey:
		curve := Curve(msg.Curve)
		if curve == "" {
			curve = CurveSecp256k1
		}
		// Verify the key exists on this node.
		info, err := n.km.GetKeyInfo(msg.GroupID, msg.KeyID, curve)
		if err != nil || info == nil {
			n.log.Warn("coord: delete-key key not found",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID))
			s.Write([]byte{coordNACK})
			return
		}
		if err := n.km.DeleteKey(msg.GroupID, msg.KeyID, curve); err != nil {
			n.log.Error("coord: delete-key failed",
				zap.String("group_id", msg.GroupID),
				zap.String("key_id", msg.KeyID),
				zap.Error(err))
			s.Write([]byte{coordNACK})
			return
		}
		n.log.Info("coord: key deleted",
			zap.String("group_id", msg.GroupID),
			zap.String("key_id", msg.KeyID))
		s.Write([]byte{coordACK})

	default:
		n.log.Warn("coord: unknown msg type", zap.Uint8("type", uint8(msg.Type)))
	}
}

// broadcastCoord sends msg to each party in targets (excluding self) over a
// direct libp2p stream, and waits for a ready ACK from each. Peer streams are
// opened in parallel so the total latency is bounded by the slowest peer rather
// than the sum of all peers.
func (n *Node) broadcastCoord(ctx context.Context, targets []tss.PartyID, msg coordMsg) error {
	self := n.host.Self()

	payload, err := cbor.Marshal(msg)
	if err != nil {
		return fmt.Errorf("marshal coord msg: %w", err)
	}

	type result struct {
		party tss.PartyID
		err   error
	}

	var peers []tss.PartyID
	for _, pid := range targets {
		if pid != self {
			peers = append(peers, pid)
		}
	}

	ch := make(chan result, len(peers))
	for _, pid := range peers {
		pid := pid
		peerID, ok := n.host.PeerForParty(pid)
		if !ok {
			return fmt.Errorf("no connected peer for party %s", pid)
		}
		go func() {
			s, err := n.host.LibP2PHost().NewStream(ctx, peerID, coordProtocol)
			if err != nil {
				ch <- result{pid, fmt.Errorf("coord stream to %s: %w", pid, err)}
				return
			}
			defer s.Close()
			if _, err := s.Write(payload); err != nil {
				ch <- result{pid, fmt.Errorf("write coord to %s: %w", pid, err)}
				return
			}
			ack := make([]byte, 1)
			if _, err := io.ReadFull(s, ack); err != nil {
				ch <- result{pid, fmt.Errorf("ack from %s: %w", pid, err)}
				return
			}
			if ack[0] == coordNACK {
				ch <- result{pid, fmt.Errorf("rejected by %s", pid)}
				return
			}
			ch <- result{pid, nil}
		}()
	}

	for range peers {
		r := <-ch
		if r.err != nil {
			return r.err
		}
		n.log.Debug("coord: party ready", zap.String("party", string(r.party)))
	}

	return nil
}
