package node

import (
	"crypto/rand"
	"crypto/rsa"
	"encoding/hex"
	"math/big"
	"os"
	"testing"
)

func TestEncodePublicInputs_MatchesBBFormat(t *testing.T) {
	// Load the known-good public_inputs generated by bb prove (via zkbench).
	expected, err := os.ReadFile("../circuits/jwt_auth/target/proof/public_inputs")
	if err != nil {
		t.Skipf("skipping: no proof artifacts: %v", err)
	}

	// Reconstruct the RSA modulus from the expected file's first 18 field elements
	// so we can verify our encoding produces an identical result.
	modulus := reconstructModulusFromPI(expected)

	proof := &AuthProof{
		JWKSModulus: modulus.Bytes(),
		Iss:         "https://accounts.example.com",
		Sub:         "user-abc-123",
		Exp:         1893456000,
		Aud:         "signet-app.example.com",
		Azp:         "client-id-456",
		SessionPub:  benchSessionPub(),
	}

	got, err := encodePublicInputs(proof)
	if err != nil {
		t.Fatalf("encodePublicInputs: %v", err)
	}

	if len(got) != len(expected) {
		t.Fatalf("length mismatch: got %d, expected %d", len(got), len(expected))
	}

	for i := range got {
		if got[i] != expected[i] {
			feIdx := i / fieldElementSize
			t.Errorf("mismatch at byte %d (field element %d):", i, feIdx)
			t.Errorf("  got:      %s", hex.EncodeToString(got[feIdx*fieldElementSize:(feIdx+1)*fieldElementSize]))
			t.Errorf("  expected: %s", hex.EncodeToString(expected[feIdx*fieldElementSize:(feIdx+1)*fieldElementSize]))
			t.FailNow()
		}
	}
}

func TestEncodePublicInputs_RoundTrip(t *testing.T) {
	key, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		t.Fatalf("generate RSA key: %v", err)
	}

	proof := &AuthProof{
		JWKSModulus: key.PublicKey.N.Bytes(),
		Iss:         "https://accounts.google.com",
		Sub:         "user-12345",
		Exp:         1893456000,
		Aud:         "my-app.example.com",
		Azp:         "client-789",
		SessionPub:  benchSessionPub(),
	}

	pi, err := encodePublicInputs(proof)
	if err != nil {
		t.Fatalf("encodePublicInputs: %v", err)
	}

	expectedLen := totalPIElements * fieldElementSize
	if len(pi) != expectedLen {
		t.Fatalf("length: got %d, expected %d", len(pi), expectedLen)
	}

	// Verify modulus round-trips through limb encoding.
	reconstructed := reconstructModulusFromPI(pi)
	if reconstructed.Cmp(key.PublicKey.N) != 0 {
		t.Errorf("modulus round-trip failed:\n  original:      %s\n  reconstructed: %s",
			key.PublicKey.N.Text(16), reconstructed.Text(16))
	}
}

func TestEncodePublicInputs_Errors(t *testing.T) {
	_, err := encodePublicInputs(&AuthProof{SessionPub: benchSessionPub()})
	if err == nil {
		t.Error("expected error for empty JWKSModulus")
	}

	_, err = encodePublicInputs(&AuthProof{
		JWKSModulus: make([]byte, 256),
		SessionPub:  make([]byte, 32),
	})
	if err == nil {
		t.Error("expected error for wrong session_pub length")
	}
}

// benchSessionPub returns the same dummy session_pub used by zkbench.
func benchSessionPub() []byte {
	pub := make([]byte, 33)
	pub[0] = 0x02
	for i := 1; i < 33; i++ {
		pub[i] = byte(i)
	}
	return pub
}

func TestVerifyBBProof_Integration(t *testing.T) {
	// End-to-end: load the proof artifacts from zkbench and verify via bb CLI.
	proofDir := "../circuits/jwt_auth/target/proof"
	proofBytes, err := os.ReadFile(proofDir + "/proof")
	if err != nil {
		t.Skipf("skipping: no proof artifacts: %v", err)
	}
	vk, err := os.ReadFile(proofDir + "/vk")
	if err != nil {
		t.Skipf("skipping: no VK: %v", err)
	}
	expectedPI, err := os.ReadFile(proofDir + "/public_inputs")
	if err != nil {
		t.Skipf("skipping: no public_inputs: %v", err)
	}

	// First verify using the raw file contents (sanity check).
	if err := verifyBBProof(proofBytes, expectedPI, vk); err != nil {
		t.Fatalf("bb verify with original files failed: %v", err)
	}

	// Now verify using our encoded public inputs.
	modulus := reconstructModulusFromPI(expectedPI)
	ap := &AuthProof{
		JWKSModulus: modulus.Bytes(),
		Iss:         "https://accounts.example.com",
		Sub:         "user-abc-123",
		Exp:         1893456000,
		Aud:         "signet-app.example.com",
		Azp:         "client-id-456",
		SessionPub:  benchSessionPub(),
	}
	encodedPI, err := encodePublicInputs(ap)
	if err != nil {
		t.Fatalf("encodePublicInputs: %v", err)
	}

	if err := verifyBBProof(proofBytes, encodedPI, vk); err != nil {
		t.Fatalf("bb verify with encoded public inputs failed: %v", err)
	}

	// Tamper with a claim and confirm verification fails.
	tampered := &AuthProof{
		JWKSModulus: modulus.Bytes(),
		Iss:         "https://evil.example.com", // wrong issuer
		Sub:         "user-abc-123",
		Exp:         1893456000,
		Aud:         "signet-app.example.com",
		Azp:         "client-id-456",
		SessionPub:  benchSessionPub(),
	}
	tamperedPI, _ := encodePublicInputs(tampered)
	if err := verifyBBProof(proofBytes, tamperedPI, vk); err == nil {
		t.Error("expected bb verify to fail with tampered issuer")
	}
}

// reconstructModulusFromPI extracts the RSA modulus from the first 18 field
// elements (120-bit limbs, LE order) by reversing the limb split.
func reconstructModulusFromPI(pi []byte) *big.Int {
	result := new(big.Int)
	for i := numModulusLimbs - 1; i >= 0; i-- {
		feBytes := pi[i*fieldElementSize : (i+1)*fieldElementSize]
		limb := new(big.Int).SetBytes(feBytes)
		result.Lsh(result, uint(limbBits))
		result.Or(result, limb)
	}
	return result
}
